apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
  labels:
    app: jenkins-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      containers:
      - name: jenkins-agent
        image: jenkins/inbound-agent:latest
        args:
          - "-url"
          - "http://192.168.56.1:8080"
          - "-secret"
          - "79e101a9a405e62bfc1fb4f5834ca618d2a341c09934e3586c75de772f7b518d"
          - "-name"
          - "k8s-agent-1"
          - "-webSocket"
          - "-workDir"
          - "/home/jenkins"
        volumeMounts:
          - name: jenkins-agent-workdir
            mountPath: /home/jenkins
      volumes:
        - name: jenkins-agent-workdir
          emptyDir: {}

